spring:
  datasource:
    url: jdbc:mysql://localhost/shop?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
        hibernate.format_sql: true
server:
  port: 8082


app:
  upload:
    shop:
      cover: /Users/lhr/Desktop/shop/cover_upload/
      pictures: /Users/lhr/Desktop/shop/pictures_upload/


