spring:
  datasource:
    url: jdbc:mysql://localhost/shop?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

  jpa:
    show-sql: false
    properties:
        hibernate.format_sql: true
server:
  port: 8088


app:
  upload:
    shop:
      cover: /Users/lhr/Desktop/shop/cover_upload/


